module CoSimTypes {
  struct PingSM {
    double I_demanda;  // (eco) de Nodo1 a Nodo2
    double V_SM;
    double P_SM;
    double I_SM;
  };

  struct PongN2 {
    double I_demanda_eco2;  // eco2 devuelto por Nodo2
    double I_demanda;       // valor de I_demanda calculado/confirmado por Nodo2
  };
};

